polls_project/polls/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote')
]

polls_project/polls/polls/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
]

polls_project/polls/poll/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls_project/polls/poll/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'poll/detail.html', {'question': question})
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse ('poll:results', args=(question.id,)))

polls_project/polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  <title>Polls Project {% block title %}{% endblock %}</title>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 m-auto">
        {% block content %} {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

polls_project/polls/templates/poll/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-primary mt-3" href="{% url 'poll:index' %}">Back To Polls</a>
<h1 class="text-center mt-5">{{question.question_text}}</h1>

{% if error_message %}
<p class="alert alert-danger">
  <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <div class="form-check">
    <input 
      type="radio"
      name="choice"
      class="form-check-input"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    >
    <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label>
  </div>
  {% endfor %}
  <input type="submit" value="Vote" class="btn btn-success btn-block mt-3">
</form>

{% endblock %}

polls_project/polls/templates/poll/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center mb-3">Poll Questions</h1>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
    <div class="card mb-3">
      <div class="card-body">
        <p class="lead">{{ question.question_text }}</p>
        <a href="{% url 'poll:detail' question.id %}" class="btn-primary btn-sm">Vote Now</a>
        <a href="{% url 'poll:results' question.id %}" class="btn-danger btn-sm">Results</a>
      </div>
    </div>
    {% endfor %}
  {% else %}
    <p>No Polls available</p>
  {% endif %}
{% endblock %}

polls_project/polls/templates/poll/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mt-3 mb-3">{{ question.question_text }}</h1>

<ul class="list-group mb-3">
  {% for choice in question.choice_set.all%}
  <li class="list-group-item">
    {{choice.choice_text}} <span class="badge badge-success float-right">{{choice.votes}} vote{{ choice.votes | pluralize }}</span>
  </li>
  {% endfor %}
</ul>


<a href="{% url 'poll:index' %}" class="btn btn-primary">Back To Polls</a>
<a href="{% url 'poll:detail' question.id %}" class="btn btn-info">Vote Again?</a>
{% endblock %}